### PR TITLE
Review package lesson

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Can also drop 9bd3808 or a284154 if desired.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
I think after introducing documentation and testing, you should mention `R CMD Check`/ `devtools::test()`, which checks the package with regard to all formal elements of a package. I think this brings it all together nicely.

**Comment by jonmcalder** [comment]
Thanks for the PR!

I left the .Rproj out intentionally because I assumed it was bad practice to nest .Rproj files within subdirectories of a repo (see https://github.com/iandurbach/datasci-fi/blob/master/docs/lesson9-material/README.md). Should I have just included it instead? I thought I saw something from Jenny Bryan somewhere that strongly advised against this so just thought I'd avoid it in case.

The other additions/corrections are cool though. Thanks. Will merge them in and push upstream.

**Comment by jonmcalder** [comment]
Pushed upstream in https://github.com/iandurbach/datasci-fi/pull/9

**Comment by lorenzwalthert** [comment]
Thanks Jon.

**Pull request closed without merging**
